package com.pixelforge.gui.screens;

import com.pixelforge.mod.ModInstaller;
import com.pixelforge.mod.ModrinthApi;
import com.pixelforge.util.RenderUtil;
import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.api.ModContainer;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.TextFieldWidget;
import net.minecraft.text.Text;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** Clean, scrollable mod manager with monochrome PixelForge styling. */
public final class ModsScreen extends Screen {
    private final Screen parent; private boolean browseMode; private TextFieldWidget searchField; private final List<ModrinthApi.ModResult> results=new ArrayList<>(); private String status=""; private boolean restartNeeded; private double scroll;
    private static final Set<String> LIBRARIES=Set.of("minecraft","java","fabricloader","fabric-api","fabric-language-kotlin","modmenu","architectury","cloth-config","yet_another_config_lib_v3","yarn");
    private static final int TEXT=0xFFFFFFFF,DIM=0xFF8A8A8A,PANEL=0xE0101010,BORDER=0x40555555;
    public ModsScreen(Screen parent){super(Text.literal("Mods"));this.parent=parent;}
    @Override protected void init(){searchField=new TextFieldWidget(textRenderer,20,44,width-40,20,Text.literal("Search"));searchField.setPlaceholder(Text.literal("Search installed mods or Modrinth..."));searchField.setMaxLength(64);searchField.setChangedListener(s->{if(browseMode&&s.trim().length()>=2){status="Searching...";ModrinthApi.searchAsync(s.trim(),list->{results.clear();results.addAll(list);status=results.isEmpty()?"No results":"";scroll=0;});}});addDrawableChild(searchField);setFocused(searchField);}
    private boolean isLibrary(ModContainer m){String id=m.getMetadata().getId().toLowerCase(Locale.ROOT);String name=m.getMetadata().getName().toLowerCase(Locale.ROOT);return LIBRARIES.contains(id)||id.startsWith("fabric-")||id.startsWith("fabric_")||id.startsWith("quilt")||id.contains("library")||name.equals("fabric api")||name.contains("fabric loader");}
    private List<ModContainer> installed(){String q=searchField==null?"":searchField.getText().trim().toLowerCase(Locale.ROOT);return FabricLoader.getInstance().getAllMods().stream().filter(m->!isLibrary(m)).filter(m->{String id=m.getMetadata().getId().toLowerCase(Locale.ROOT),n=m.getMetadata().getName().toLowerCase(Locale.ROOT);return q.isEmpty()||id.contains(q)||n.contains(q);}).toList();}
    @Override public void render(DrawContext c,int mx,int my,float d){RenderUtil.fill(c,0,0,width,height,0x78000000);RenderUtil.drawRoundedPanel(c,12,12,width-24,height-24,PANEL,0x55FFFFFF);RenderUtil.drawText(c,textRenderer,"MOD MANAGER",24,24,TEXT,false);tab(c,"Installed",130,!browseMode,mx,my);tab(c,"Browse Modrinth",205,browseMode,mx,my);searchField.render(c,mx,my,d);int top=70,bottom=height-28;if(restartNeeded){RenderUtil.fill(c,20,70,width-20,92,0x30FFFFFF);RenderUtil.drawBorder(c,20,70,width-40,22,0x75FFFFFF);RenderUtil.drawText(c,textRenderer,"Restart required after installing a mod",28,77,TEXT,false);top=98;}if(browseMode){if(!status.isEmpty())RenderUtil.drawText(c,textRenderer,status,24,top,DIM,false);int y=top+(status.isEmpty()?0:18)-(int)scroll;c.enableScissor(18,top,width-18,bottom);for(ModrinthApi.ModResult mod:results){if(y+34>=top&&y<=bottom)drawRow(c,22,y,width-44,mod.title,mod.description,true,mod.projectId);y+=40;}c.disableScissor();drawScrollbar(c,top,bottom,results.size(),40);}else{List<ModContainer> mods=installed();int y=top-(int)scroll;c.enableScissor(18,top,width-18,bottom);for(ModContainer mod:mods){if(y+34>=top&&y<=bottom){String id=mod.getMetadata().getId();drawRow(c,22,y,width-44,mod.getMetadata().getName(),mod.getMetadata().getVersion().getFriendlyString()+" · "+id,false,id);}y+=40;}c.disableScissor();drawScrollbar(c,top,bottom,mods.size(),40);}if(!status.isEmpty()&&!browseMode)RenderUtil.drawText(c,textRenderer,status,24,height-16,status.startsWith("Installed")?TEXT:0xFFFF7777,false);RenderUtil.drawText(c,textRenderer,"ESC  •  mouse wheel scroll",24,height-16,DIM,false);super.render(c,mx,my,d);}
    private void tab(DrawContext c,String label,int x,boolean on,int mx,int my){int w=textRenderer.getWidth(label);RenderUtil.drawText(c,textRenderer,label,x,24,TEXT,false);if(on)RenderUtil.fill(c,x,40,x+w,42,0xFFFFFFFF);}
    private void drawRow(DrawContext c,int x,int y,int w,String name,String sub,boolean browse,String modId){RenderUtil.fill(c,x,y,x+w,y+34,0x16FFFFFF);RenderUtil.drawBorder(c,x,y,w,34,BORDER);drawIcon(c,modId,x+7,y+7,20);RenderUtil.drawText(c,textRenderer,name,x+34,y+6,TEXT,false);String s=sub==null?"":sub.replace('\n',' ');if(s.length()>58)s=s.substring(0,55)+"...";RenderUtil.drawText(c,textRenderer,s,x+34,y+18,DIM,false);if(browse){RenderUtil.fill(c,x+w-72,y+8,x+w-8,y+26,0x24FFFFFF);RenderUtil.drawBorder(c,x+w-72,y+8,64,18,0x75FFFFFF);RenderUtil.drawText(c,textRenderer,"Install",x+w-59,y+13,TEXT,false);}}
    private void drawIcon(DrawContext c,String modId,int x,int y,int size){int hash=modId==null?0:modId.hashCode();int r=60+(Math.abs(hash)%120),g=70+(Math.abs(hash>>8)%110),b=120+(Math.abs(hash>>16)%100);int bg=0xFF000000|(r<<16)|(g<<8)|b;RenderUtil.fill(c,x,y,x+size,y+size,bg);RenderUtil.drawBorder(c,x,y,size,size,0x75FFFFFF);String letter=(modId!=null&&!modId.isEmpty())?modId.substring(0,1).toUpperCase(Locale.ROOT):"?";RenderUtil.drawCenteredText(c,textRenderer,letter,x+size/2,y+6,0xFFFFFFFF,false);}
    private void drawScrollbar(DrawContext c,int top,int bottom,int count,int rowH){int content=count*rowH,view=bottom-top;if(content<=view)return;int thumb=Math.max(18,(int)(view*(view/(double)content)));int max=Math.max(1,content-view);int ty=top+(int)((view-thumb)*(scroll/max));RenderUtil.fill(c,width-9,top,width-6,bottom,0x30FFFFFF);RenderUtil.fill(c,width-9,ty,width-6,ty+thumb,0xAAFFFFFF);}
    @Override public boolean mouseScrolled(double mx,double my,double horizontal,double vertical){if(my>=40&&my<=height-20){int count=browseMode?results.size():installed().size();int max=Math.max(0,count*40-(height-70-22));scroll=Math.max(0,Math.min(max,scroll-vertical*28));return true;}return super.mouseScrolled(mx,my,horizontal,vertical);}
    @Override public boolean mouseClicked(net.minecraft.client.gui.Click click,boolean doubled){double mx=click.x(),my=click.y();int b=click.button();if(my<42&&b==0){if(mx>=120&&mx<190){browseMode=false;scroll=0;return true;}if(mx>=195&&mx<330){browseMode=true;scroll=0;return true;}}if(browseMode){int top=70;int y=top-(int)scroll;for(ModrinthApi.ModResult mod:results){if(mx>=width-88&&my>=y+8&&my<=y+26){status="Installing "+mod.title+"...";ModInstaller.install(mod,ok->{if(ok){status="Installed "+mod.title;restartNeeded=true;}else status="Install failed";});return true;}y+=40;}}if(searchField.mouseClicked(click,doubled)){setFocused(searchField);return true;}return super.mouseClicked(click,doubled);}
    @Override public boolean keyPressed(net.minecraft.client.input.KeyInput i){if(i.key()==256){client.setScreen(parent);return true;}if(searchField.isFocused()&&searchField.keyPressed(i))return true;return super.keyPressed(i);}
    @Override public boolean charTyped(net.minecraft.client.input.CharInput i){if(searchField.isFocused()&&searchField.charTyped(i))return true;return super.charTyped(i);}
    @Override public boolean shouldPause(){return false;}
}
